// Dados de ranks e preços para cada jogo
import { GameRanks } from './types';

export const GAME_RANKS: GameRanks = {
  'rocket-league': [
    { id: 'bronze-1', name: 'Bronze I', price: 15 },
    { id: 'bronze-2', name: 'Bronze II', price: 18 },
    { id: 'bronze-3', name: 'Bronze III', price: 22 },
    { id: 'silver-1', name: 'Silver I', price: 28 },
    { id: 'silver-2', name: 'Silver II', price: 35 },
    { id: 'silver-3', name: 'Silver III', price: 42 },
    { id: 'gold-1', name: 'Gold I', price: 50 },
    { id: 'gold-2', name: 'Gold II', price: 60 },
    { id: 'gold-3', name: 'Gold III', price: 70 },
    { id: 'platinum-1', name: 'Platinum I', price: 85 },
    { id: 'platinum-2', name: 'Platinum II', price: 100 },
    { id: 'platinum-3', name: 'Platinum III', price: 120 },
    { id: 'diamond-1', name: 'Diamond I', price: 150 },
    { id: 'diamond-2', name: 'Diamond II', price: 180 },
    { id: 'diamond-3', name: 'Diamond III', price: 220 },
    { id: 'champion-1', name: 'Champion I', price: 280 },
    { id: 'champion-2', name: 'Champion II', price: 350 },
    { id: 'champion-3', name: 'Champion III', price: 450 },
    { id: 'grand-champion', name: 'Grand Champion', price: 600 },
  ],
  'csgo': [
    { id: 'silver-1', name: 'Silver I', price: 20 },
    { id: 'silver-2', name: 'Silver II', price: 25 },
    { id: 'silver-3', name: 'Silver III', price: 30 },
    { id: 'silver-4', name: 'Silver IV', price: 35 },
    { id: 'silver-elite', name: 'Silver Elite', price: 40 },
    { id: 'silver-elite-master', name: 'Silver Elite Master', price: 50 },
    { id: 'gold-nova-1', name: 'Gold Nova I', price: 60 },
    { id: 'gold-nova-2', name: 'Gold Nova II', price: 70 },
    { id: 'gold-nova-3', name: 'Gold Nova III', price: 80 },
    { id: 'gold-nova-master', name: 'Gold Nova Master', price: 95 },
    { id: 'mg-1', name: 'Master Guardian I', price: 110 },
    { id: 'mg-2', name: 'Master Guardian II', price: 130 },
    { id: 'mge', name: 'Master Guardian Elite', price: 150 },
    { id: 'dmg', name: 'Distinguished Master Guardian', price: 180 },
    { id: 'le', name: 'Legendary Eagle', price: 220 },
    { id: 'lem', name: 'Legendary Eagle Master', price: 280 },
    { id: 'supreme', name: 'Supreme Master First Class', price: 350 },
    { id: 'global', name: 'Global Elite', price: 500 },
  ],
  'valorant': [
    { id: 'iron-1', name: 'Iron 1', price: 18 },
    { id: 'iron-2', name: 'Iron 2', price: 22 },
    { id: 'iron-3', name: 'Iron 3', price: 26 },
    { id: 'bronze-1', name: 'Bronze 1', price: 32 },
    { id: 'bronze-2', name: 'Bronze 2', price: 38 },
    { id: 'bronze-3', name: 'Bronze 3', price: 45 },
    { id: 'silver-1', name: 'Silver 1', price: 55 },
    { id: 'silver-2', name: 'Silver 2', price: 65 },
    { id: 'silver-3', name: 'Silver 3', price: 75 },
    { id: 'gold-1', name: 'Gold 1', price: 90 },
    { id: 'gold-2', name: 'Gold 2', price: 105 },
    { id: 'gold-3', name: 'Gold 3', price: 125 },
    { id: 'platinum-1', name: 'Platinum 1', price: 150 },
    { id: 'platinum-2', name: 'Platinum 2', price: 180 },
    { id: 'platinum-3', name: 'Platinum 3', price: 220 },
    { id: 'diamond-1', name: 'Diamond 1', price: 280 },
    { id: 'diamond-2', name: 'Diamond 2', price: 350 },
    { id: 'diamond-3', name: 'Diamond 3', price: 450 },
    { id: 'ascendant-1', name: 'Ascendant 1', price: 550 },
    { id: 'ascendant-2', name: 'Ascendant 2', price: 650 },
    { id: 'ascendant-3', name: 'Ascendant 3', price: 800 },
    { id: 'immortal', name: 'Immortal', price: 1000 },
    { id: 'radiant', name: 'Radiant', price: 1500 },
  ],
  'fortnite': [
    { id: 'bronze', name: 'Bronze', price: 25 },
    { id: 'silver', name: 'Silver', price: 40 },
    { id: 'gold', name: 'Gold', price: 60 },
    { id: 'platinum', name: 'Platinum', price: 90 },
    { id: 'diamond', name: 'Diamond', price: 130 },
    { id: 'elite', name: 'Elite', price: 180 },
    { id: 'champion', name: 'Champion', price: 250 },
    { id: 'unreal', name: 'Unreal', price: 400 },
  ],
  'lol': [
    { id: 'iron-4', name: 'Iron IV', price: 20 },
    { id: 'iron-3', name: 'Iron III', price: 24 },
    { id: 'iron-2', name: 'Iron II', price: 28 },
    { id: 'iron-1', name: 'Iron I', price: 32 },
    { id: 'bronze-4', name: 'Bronze IV', price: 38 },
    { id: 'bronze-3', name: 'Bronze III', price: 45 },
    { id: 'bronze-2', name: 'Bronze II', price: 52 },
    { id: 'bronze-1', name: 'Bronze I', price: 60 },
    { id: 'silver-4', name: 'Silver IV', price: 70 },
    { id: 'silver-3', name: 'Silver III', price: 82 },
    { id: 'silver-2', name: 'Silver II', price: 95 },
    { id: 'silver-1', name: 'Silver I', price: 110 },
    { id: 'gold-4', name: 'Gold IV', price: 130 },
    { id: 'gold-3', name: 'Gold III', price: 150 },
    { id: 'gold-2', name: 'Gold II', price: 175 },
    { id: 'gold-1', name: 'Gold I', price: 200 },
    { id: 'platinum-4', name: 'Platinum IV', price: 240 },
    { id: 'platinum-3', name: 'Platinum III', price: 280 },
    { id: 'platinum-2', name: 'Platinum II', price: 330 },
    { id: 'platinum-1', name: 'Platinum I', price: 380 },
    { id: 'diamond-4', name: 'Diamond IV', price: 450 },
    { id: 'diamond-3', name: 'Diamond III', price: 550 },
    { id: 'diamond-2', name: 'Diamond II', price: 650 },
    { id: 'diamond-1', name: 'Diamond I', price: 800 },
    { id: 'master', name: 'Master', price: 1000 },
    { id: 'grandmaster', name: 'Grandmaster', price: 1500 },
    { id: 'challenger', name: 'Challenger', price: 2500 },
  ],
  'apex': [
    { id: 'bronze-4', name: 'Bronze IV', price: 22 },
    { id: 'bronze-3', name: 'Bronze III', price: 28 },
    { id: 'bronze-2', name: 'Bronze II', price: 34 },
    { id: 'bronze-1', name: 'Bronze I', price: 40 },
    { id: 'silver-4', name: 'Silver IV', price: 50 },
    { id: 'silver-3', name: 'Silver III', price: 60 },
    { id: 'silver-2', name: 'Silver II', price: 72 },
    { id: 'silver-1', name: 'Silver I', price: 85 },
    { id: 'gold-4', name: 'Gold IV', price: 100 },
    { id: 'gold-3', name: 'Gold III', price: 120 },
    { id: 'gold-2', name: 'Gold II', price: 140 },
    { id: 'gold-1', name: 'Gold I', price: 165 },
    { id: 'platinum-4', name: 'Platinum IV', price: 195 },
    { id: 'platinum-3', name: 'Platinum III', price: 230 },
    { id: 'platinum-2', name: 'Platinum II', price: 270 },
    { id: 'platinum-1', name: 'Platinum I', price: 320 },
    { id: 'diamond-4', name: 'Diamond IV', price: 380 },
    { id: 'diamond-3', name: 'Diamond III', price: 450 },
    { id: 'diamond-2', name: 'Diamond II', price: 550 },
    { id: 'diamond-1', name: 'Diamond I', price: 650 },
    { id: 'master', name: 'Master', price: 850 },
    { id: 'predator', name: 'Predator', price: 1200 },
  ],
};

export const GAME_NAMES: Record<string, string> = {
  'rocket-league': 'Rocket League',
  'csgo': 'CS:GO',
  'valorant': 'Valorant',
  'fortnite': 'Fortnite',
  'lol': 'League of Legends',
  'apex': 'Apex Legends',
};

export const URGENCY_MULTIPLIERS = {
  normal: 1,
  fast: 1.5,
  express: 2,
};

export const URGENCY_LABELS = {
  normal: 'Normal (7-10 dias)',
  fast: 'Rápido (3-5 dias) +50%',
  express: 'Expresso (1-2 dias) +100%',
};
